title: EEF CNA
description: This project handles the CVE Numbering Authority (CNA) for the Erlang Ecosystem Foundation (EEF).
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-datapage-generator
page_gen-dirs: true
page_gen:
- data: cves
  template: cve
  dir: cves
  index_files: false
  name_expr: 'record["cveMetadata"]["cveId"]'
  title_expr: 'record["containers"]["cna"]["title"] || record["cveMetadata"]["cveId"]'
